### ISSUE TITLE
Wrong calculation of PA and UA standard error

### ISSUE THREAD

**Issue by jonasViehweger** [hagc/mapaccuracy#1]
https://github.com/hagc/mapaccuracy/blob/ee73f54848ac2a69c07a67faed3df7d6b4702b15/R/stehman2014.R#L275

`nh` is passed incorrectly to the `eq28` function. It should be `nh=nh` instead of `nh=nh[i]`.
The same issue also has to be fixed on line 284.

**Comment by hagc** [comment]
Thank for spotting this bug. Fortunately, it impacts only the cases with varying sample size across strata, which is not so common. I'll release a new version of the package just to fix this.
